version: "3.3"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - ../../grafana/data:/var/lib/grafana # data path
      - ../../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "1000"
    volumes:
      - ../../prometheus:/prometheus
    command: "--config.file=/prometheus/prometheus.yaml --query.lookback-delta='16s'"
    ports:
      - 9090:9090
    restart: always
